### ISSUE TITLE
Make crate more reusable

### ISSUE THREAD

**Issue by Colerar** [imbolc/axum-client-ip#18]
For example, the `SecureClientIp::from_request_parts` API is public, but its requirement is too strict.

https://github.com/imbolc/axum-client-ip/blob/bf0579e0bff4997e9a292eaa1ea2a2245df33f2a/src/secure.rs#L85

Caller needs to pass a `&mut Parts` and a meaningless `&()` to fill the `state` argument, and the function is `async`, so it cannot be called in non-async context.

We can simply modify [`SecureClientIp::from_parts`](https://github.com/imbolc/axum-client-ip/blob/bf0579e0bff4997e9a292eaa1ea2a2245df33f2a/src/secure.rs#L53-L75) so it can be used by other crates:

```rust
pub fn from(
    ip_source: &SecureClientIpSource,
    headers: &HeaderMap<HeaderValue>,
    extensions: &Extensions,
) -> Result<Self, StringRejection> {
    match ip_source {
        SecureClientIpSource::RightmostForwarded => Forwarded::rightmost_ip(headers),
        SecureClientIpSource::RightmostXForwardedFor => XForwardedFor::rightmost_ip(headers),
        SecureClientIpSource::XRealIp => XRealIp::ip_from_headers(headers),
        SecureClientIpSource::FlyClientIp => FlyClientIp::ip_from_headers(headers),
        SecureClientIpSource::TrueClientIp => TrueClientIp::ip_from_headers(headers),
        SecureClientIpSource::CfConnectingIp => CfConnectingIp::ip_from_headers(headers),
        SecureClientIpSource::ConnectInfo => extensions
            .get::<ConnectInfo<SocketAddr>>()
            .map(|ConnectInfo(addr)| addr.ip())
            .ok_or_else(|| {
                "Can't extract `SecureClientIp`, provide `axum::extract::ConnectInfo`".into()
            }),
    }
    .map(Self)
}
```

Furthermore, I think we can extract the core function of this crate into another separate crate to avoid copying and pasting:

https://github.com/benwis/tower-governor/blob/df3d175e28c6989ff5e388c8baa990fd440163ba/src/key_extractor.rs#L125-L171

**Comment by imbolc** [comment]
Hey :)

As you'd probably agree, making more api public or splitting crates implies additional maintenance burden. E.g. there's no copied code you've mentioned in the current version of the crate ;) So I'd prefer avoiding this until there's a practical need that outweighs the cost.

Saying that, I'm ok with adding the `pub fn from` and using it in the `from_request_parts`, if you need it. Would you create a PR?

> we can extract the core function of this crate into another separate crate

Would the goal of the separate crate be removing Axum from dependencies and the crate name? I've just skimmed through the code and don't see parts that can't be easily extracted, do you?

Ideally, I'd envision the crate `client-ip` with features like `axum`, `actix` etc. I believe it would bring more security into the world ;) E.g. this crate was just its current `insecure` part and achieved its current form after users reported the security issues in #6. Though I personally have other priorities right now rather than making it ;)

**Comment by imbolc** [comment]
> So the approach publishing a `client-ip` crate with features seems to only work for the end application.

Why? E.g. if we hide everything related to Axum under a feature flag, what's left could be used exactly as the crate you're going to extract.

**Comment by imbolc** [comment]
Published, thank you :pray:
